const videos = [
  {
    title:
      "Perfect Forehand in 3 Easy Steps - Tennis Forehand Technique Lesson",
    thumbnail:
      "https://i.ytimg.com/vi/5arVdubK9Pg/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAAJGYiGfX7PD_3f2tIDXsFyQ4gDQ",
    tags: ["tennis", "sport", "Top Tennis Training - Pro Tennis Lessons"],
    category: ["forehand"],
    uploaded: "May 9, 2020",
    url: `https://youtube.com/embed/5arVdubK9Pg`,
    channel: {
      name: "Top Tennis Training - Pro Tennis Lessons",
      logo: "https://yt3.ggpht.com/ytc/AAUvwnidEDJaEpS0DizbYD_4EE7nL5EsalhRc4P80xIuVw=s88-c-k-c0x00ffffff-no-rj",
    },
    statistics: {
      views: 289071,
      likes: 3900,
      dislikes: 90,
    },
    description: `
          Perfect Forehand in 3 Easy Steps - Tennis Forehand Technique Lesson.
          We all love the feeling of hitting the perfect forehand when you are timing the shot and giving the ball just the right amount of power and spin in a relaxed way. In order to stay fully relaxed and produce effortless power and spin, we need to make sure we follow 3 simple steps to achieve this.
          1. The take-back - making sure you have a deep swing but one that is generated by the body turn (unit turn) separating your shoulders from your hip and creating a nice coiling effect. The left-arm going across the body will help you do this and ensure you are not taking your racquet back too far. Make sure your racquet head does not bend behind the body for ATP Forehand so keep the racquet on your right. WTA Forehand players tend to let it go behind for more power and racquet momentum but less wrist snap and less ability to create top-spin.
          2. The contact - this will ensure the direction of the ball so it is vital you have the racquet face pointing away from you slightly in front (somewhere around where you front toe is). The path of the racquet needs to continue going in a linear way as much as possible through contact (avoid the semi-circle) and don't pull your arm across your body.
          3. The finish - ensuring a good follow-through is vital. Don't stop your arm, let it go through all the way to stay loose and smooth. having a high elbow finish helps get a nice low to high trajectory and also makes it easy to apply topspin as its easier to rotate your wrist. Even if you do not finish in a classic way over your shoulder still ensure to have a high elbow.
          This video is for those of you wondering how to hit a tennis forehand or how to hit a forehand in tennis. Enjoy!
          If you enjoyed this video support us by becoming our TTT Squad channel member here - https://www.youtube.com/channel/UCNOh...
          Chapters
          00:00 - Perfect Tennis Forehand
          00:17 - Perfect Forehand Swing in Tennis
          01:21 - Perfect Forehand Contact Point in Tennis
          02:26 - Perfect Forehand Finish in Tennis`,
  },
  {
    title:
      "Tennis Forehand Transformation - Technique For Maximum Power and Control",
    thumbnail:
      "https://i.ytimg.com/vi/-sZ3madzfoA/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCI8dOoXKjdu_Cqu428oSeAD60A9g",
    tags: [
      "tennis",
      "sport",
      "TennisForehand",
      "Top Tennis Training - Pro Tennis Lessons",
    ],
    category: ["forehand"],
    uploaded: "Apr 29, 2019",
    url: "https://youtube.com/embed/-sZ3madzfoA",
    channel: {
      name: "Top Tennis Training - Pro Tennis Lessons",
      logo: "https://yt3.ggpht.com/ytc/AAUvwnidEDJaEpS0DizbYD_4EE7nL5EsalhRc4P80xIuVw=s88-c-k-c0x00ffffff-no-rj",
    },
    statistics: {
      views: 1369681,
      likes: 23000,
      dislikes: 415,
    },
    description: `
      Tennis Forehand Transformation - Technique For Maximum Power and Control. In this video lesson, Top Tennis Training coach Simon Konov is working on his student's forehand technique, the player struggles with timing, power and consistency on his forehand. The key elements that they focus on are:
      Early preparation on the forehand with the racket and non-hitting separating earlier in the swing, if the left-hand stays on the racket for too long the player will struggle with timing the contact in front of the body. 
      Reaching a good power position on the forehand - if the non-hitting hand stays on the racket for too long the end result will be rushing during the forward phase of the swing but it also means the player doesn't reach a good power position. The power position is where the non-hitting hand is across the body, almost in line with the baseline, the racket head is higher than the grip level creating leverage in the racket and hand and the body is coiled up, ready to uncoil on the forward phase of the swing.
      Weight transfer and full rotation - Simon's student struggles to open up the shoulders fully on the finish and this blocks the amount of power he can generate. By uncoiling fully on the forward phase you can generate maximum power and control of the shot plus the weight transfer becomes much easier when done correctly.
      Video timeline:
      00:00 - Intro
      00:32 - Students Forehand At The Start of Lesson
      1:20 - Too Slow Preparation (analysis one)
      3:01 - Too Big Backswing (analysis two)
      5:18 - Drills To Correct Bad Habits
      Subscribe to our channel here - https://bit.ly/2V1F13c
      Make sure you turn on the notification bell 🔔 
      #Tennis #TennisForehand #TennisLesson`,
  },
  {
    title: "Simple Tennis Forehand Power Trick | Tennis Forehand Lesson",
    thumbnail:
      "https://i.ytimg.com/vi/OW9bUB5C5tA/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCYTp8dDOPNkGAxrtgpwoHidG30xQ",
    tags: [
      "tennis",
      "sport",
      "TennisForehand",
      "Top Tennis Training - Pro Tennis Lessons",
    ],
    category: ["forehand"],
    uploaded: "Aug 30, 2016",
    url: "https://youtube.com/embed/OW9bUB5C5tA",
    channel: {
      name: "Top Tennis Training - Pro Tennis Lessons",
      logo: "https://yt3.ggpht.com/ytc/AAUvwnidEDJaEpS0DizbYD_4EE7nL5EsalhRc4P80xIuVw=s88-c-k-c0x00ffffff-no-rj",
    },
    statistics: {
      views: 417700,
      likes: 3300,
      dislikes: 91,
    },
    description: `  
              Simple Tennis Forehand Power Trick - Tennis Forehand Lesson
              In this video, Top Tennis Training coach Simon Konov will help you get more power on your forehand with one simple trick.
              The key to more power on any shot is racket head speed. Leverage on any shot will give you the force over the ball, but also allow the space to accelerate your racket in the most energy-efficient way.
              By simply starting your forehand with the racket head up like Roger Federer, Stan Wawrinka, Novak Djokovic, and Rafael Nadal you will be gaining more leverage right from the start of the stroke along with saving time later in the swing with the lag position.
              Video timeline:
              00:00 - What is lag?
              1:42 - How to create lag on your forehand
              2:29 - Power position and racket lag
              3:22 - How to feel lag
              Subscribe to our channel here - https://bit.ly/2V1F13c
              Make sure you turn on the notification bell 🔔
              #tennis #tennisforehand #forehandlag
              `,
  },
  {
    title: "Beginner Tennis Lesson | Forehand, Backhand & Serve",
    thumbnail:
      "https://i.ytimg.com/vi/YqgcykDGB2A/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLD5CzNnyD-avBUvqiR22hac3NnJ3w",
    tags: ["tennis", "sport", "TennisForehand", "training", "intuitive tennis"],
    category: ["forehand"],
    uploaded: "Aug 11, 2020",
    url: "https://youtube.com/embed/YqgcykDGB2A",
    channel: {
      name: "Intuitive Tennis",
      logo: "https://yt3.ggpht.com/ytc/AAUvwng1rygM9tMLbhN5T9-Aal8reInZoDBkf8kYJ9wC0A=s88-c-k-c0x00ffffff-no-rj",
    },
    statistics: {
      views: 956328,
      likes: 14000,
      dislikes: 316,
    },
    description: `  
      In this beginner tennis lesson, I teach my student Anna how to hit the forehand, backhand and the serve. If you have never played before you can follow the tips in this video to get started with tennis.
      0:00 Beginner Forehand 
      7:09 Beginner Backhand 
      11:31 Changing Grips
      15:33 Beginner Serve
              `,
  },
  {
    title:
      "Tennis Forehand Topspin - 3 Ways To Get More Topspin On Your Forehand",
    thumbnail:
      "https://i.ytimg.com/vi/Rm08-qbXeW8/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDLUJVJmXSrKWCTtfi_phR6MlVl5Q",
    tags: ["tennis", "sport", "TennisForehand", "training", "intuitive tennis"],
    category: ["forehand"],
    uploaded: "Jul 1, 2019",
    url: "https://youtube.com/embed/Rm08-qbXeW8",
    channel: {
      name: "Top Tennis Training - Pro Tennis Lessons",
      logo: "https://yt3.ggpht.com/ytc/AAUvwnidEDJaEpS0DizbYD_4EE7nL5EsalhRc4P80xIuVw=s88-c-k-c0x00ffffff-no-rj",
    },
    statistics: {
      views: 177719,
      likes: 4000,
      dislikes: 39,
    },
    description: `
          Tennis Forehand Topspin - 3 Ways To Get More Topspin On Your Forehand. Tennis players around the world want to generate more topspin on their forehands but don't know how to do so. In this tennis video lesson, coach Simon Konov of Top Tennis Training will show you three different ways to get massive topspin on your tennis forehand. 
          When we want more power on our tennis forehand, it's important to try to flatten out the shot and extend the racket and hand towards our target, so the swing path becomes a more linear one.
          When we want more topspin however, the spin path changes to a more vertical one. Imagine the ball as a clock face, six o'clock at the bottom and twelve o'clock at the top, when we want to hit with more topspin on our forehands, we want to try to brush upwards on the ball going from six to twelve o'clock. This vertical swing path allows us to use a low to high racket path.
          Here are the three steps to getting more topspin on your forehand in tennis:
          Step One - Using a low to high swing path which will allow you to brush upwards on the ball. 6-12 o'clock on the clock face.
          Step Two - Dropping the racket head below the contact point. Many players struggle with this step, they tend to bring the racket head on the same level as the ball and then brush up, so they only use 50% of their upwards potential. Try to feel the entire racket head has dropped below the contact point which will allow you to brush upwards fully during the contact zone.
          Step Three - Using the legs to drive upwards on the ball. When you want more topspin on your forehand, it's a good idea to use an open-stance forehand or a semi-open stance forehand. This will allow you to really load up on the outside leg which is the right leg for right-handed players, then push up off the ground creating good ground force which will result in a more explosive upwards motion with the racket.
          #tennis #forehand #topspin`,
  },
  //   backhand
  {
    title:
      "How To Hit A Tennis Backhand | Modern One Handed Backhand in 3 Steps",
    thumbnail:
      "https://i.ytimg.com/vi/hKSr14cUn9Q/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCYq4YNMqwTowIFR8gqWJ-8Ce2L3A",
    tags: [
      "tennis",
      "sport",
      "TennisBackhand",
      "training",
      "Top Tennis Training - Pro Tennis Lessons",
    ],
    category: ["backhand"],
    uploaded: "May 2, 2014",
    url: "https://youtube.com/embed/hKSr14cUn9Q",
    channel: {
      name: "Top Tennis Training - Pro Tennis Lessons",
      logo: "https://yt3.ggpht.com/ytc/AAUvwnidEDJaEpS0DizbYD_4EE7nL5EsalhRc4P80xIuVw=s88-c-k-c0x00ffffff-no-rj",
    },
    statistics: {
      views: 1539543,
      likes: 24000,
      dislikes: 350,
    },
    description: `Master your single-handed backhand, by Top Tennis Training.
      Video Timeline:
      00:00 - Intro
      00:24 - Unit Turn (step one)
      1:25 - Power Position (step two)
      3:04 - Follow Through and Finish (step three)
      Subscribe to our channel here - https://bit.ly/2V1F13c
      Make sure you turn on the notification bell 🔔 
      #Tennis #TennisBackhand #TennisLesson`,
  },
  {
    title: "Tennis Two Handed Backhand - 3 Steps To The Perfect Double Hander",
    thumbnail:
      "https://i.ytimg.com/vi/PBguk3yRPgI/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAs1SATHWlcyjJ7J8aG-E6phEwzlw",
    tags: [
      "tennis",
      "sport",
      "TennisBackhand",
      "training",
      "Top Tennis Training - Pro Tennis Lessons",
    ],
    category: ["backhand"],
    uploaded: "Oct 17, 2016",
    irl: "https://youtube.com/embed/PBguk3yRPgI",
    channel: {
      name: "Top Tennis Training - Pro Tennis Lessons",
      logo: "https://yt3.ggpht.com/ytc/AAUvwnidEDJaEpS0DizbYD_4EE7nL5EsalhRc4P80xIuVw=s88-c-k-c0x00ffffff-no-rj",
    },
    statistics: {
      views: 806969,
      likes: 10000,
      dislikes: 220,
    },
    description: `Tennis Two-Handed Backhand | 3 Steps To The Perfect Two Hander
      In this video Top Tennis Training coaches, Simon Konov and Alex Slabinsky will help you perfect your double-handed backhand using 3 simple steps.
      The initial thing to focus on is your grip and how you wait in the ready position. After you identify that the ball is coming to your backhand, the 3 steps are - 
      1. A good unit turn and moving sideways onto the ball (can have your chin touching your right shoulder in this position to aid the turn)
      2. Reaching a good power position with the racket head up higher than the grip level generating good leverage (force over the ball) and space to accelerate the racket
      3. A good finish with a full rotation of the shoulders and hips, including the back leg and finishing with the racket and arms over your right shoulder (if right-handed) 
      Follow these three steps and you will see a huge difference already in your backhand.
      Video Timeline:
      00:00 Intro
      00:22 - Which grip should you wait with?
      2:14 - Unit Turn (step one)
      4:17 - Power Position (step two)
      8:26 - The Finish (step three)
      `,
  },
  {
    title: "Avoid This Mistake on Your Two Handed Backhand Tennis Technique",
    thumbnail:
      "https://i.ytimg.com/vi/N4D9HNumgQo/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCWGBxOUzCbhhKFlMFVQtc2J1yuew",
    tags: ["tennis", "sport", "TennisBackhand", "training", "Intuitive Tennis"],
    category: ["backhand"],
    uploaded: "Nov 20, 2020",
    url: "https://youtube.com/embed/N4D9HNumgQo",
    channel: {
      name: "Intuitive Tennis",
      logo: "https://yt3.ggpht.com/ytc/AAUvwng1rygM9tMLbhN5T9-Aal8reInZoDBkf8kYJ9wC0A=s88-c-k-c0x00ffffff-no-rj",
    },
    statistics: {
      views: 72579,
      likes: 1400,
      dislikes: 16,
    },
    description: `Avoid making this mistake on your two handed backhand tennis technique that occurs at the junior, recreational, and even at the professional level.`,
  },
  {
    title:
      "Novak Djokovic Backhand Slow Motion - ATP Tennis Two Handed Backhand Technique",
    thumbnail:
      "https://i.ytimg.com/vi/6WyMFz4ynl4/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAJaVZOS_hUqbhoGk-Cdhej2HvrRg",
    tags: ["tennis", "sport", "TennisBackhand", "training", "Love Tennis"],
    category: ["backhand"],
    uploaded: "May 17, 2020",
    url: "https://youtube.com/embed/6WyMFz4ynl4",
    channel: {
      name: "Love Tennis",
      logo: "https://yt3.ggpht.com/ytc/AAUvwnj8uXXuL-PyZnFUfU5Kd7lmIHtEwCKyl2e2EqSZ1Q=s88-c-k-c0x00ffffff-no-rj",
    },
    statistics: {
      views: 219161,
      likes: 1200,
      dislikes: 37,
    },
    description: `Novak Djokovic Backhand Slow Motion - ATP Tennis Two Handed Backhand Technique. Arguably the best backhand in tennis ever, Novak Djokovic Backhand technique is simple, yet flawless and smooth which allows him to generate both power and top spin from anywhere on the court. When dealing with pace Djokovic blocks and jabs the ball on his backhand but can also redirect and counter attack even when on the run.`,
  },
  {
    title: "How To Hit Your Backhand Like Roger Federer",
    thumbnail:
      "https://i.ytimg.com/vi/uR1bBB8WY1g/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCV6UslLBQz5aNl8IhGaLT5C5BI-Q",
    tags: ["tennis", "sport", "TennisBackhand", "training", "HUGE TENNIS"],
    category: ["backhand"],
    uploaded: "Jul 4, 2017",
    url: "https://youtube.com/embed/uR1bBB8WY1g",
    channel: {
      name: "HUGE TENNIS",
      logo: "https://yt3.ggpht.com/ytc/AAUvwnhpd0N7hpxyeTTwV0q9NSBPba-_U0lsMGCfNJjl8g=s88-c-k-c0x00ffffff-no-rj",
    },
    statistics: {
      views: 727870,
      likes: 6800,
      dislikes: 326,
    },
    description: ``,
  },
  //   grips
  {
    title: "Tennis Grips Explained - Tennis Lesson - Grips Instruction",
    thumbnail:
      "https://i.ytimg.com/vi/cJCyMldkGM8/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDY4Ru1Go9ypxQNlkeij4pXZ63RIw",
    tags: ["tennis", "sport", "Tennis Grip"],
    category: ["grip"],
    uploaded: "Jul 4, 2017",
    url: "https://youtube.com/embed/cJCyMldkGM8",
    channel: {
      name: "Essential Tennis - Lessons and Instruction for Passionate Players",
      logo: "https://yt3.ggpht.com/ytc/AAUvwng8rPyGGrs6Kzgq5x16ssURV-jeejchRp5Y9daYGg=s88-c-k-c0x00ffffff-no-rj",
    },
    statistics: {
      views: 484289,
      likes: 8700,
      dislikes: 100,
    },
    description: ``,
  },
  {
    title: "Best Tennis Forehand Grip",
    thumbnail:
      "https://i.ytimg.com/vi/o0BD3ok6Vq8/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLChjbvqUHDtApJhSht3Vfpur_rQjQ",
    tags: ["tennis", "sport", "TennisGrip"],
    category: ["grip"],
    uploaded: "Apr 10, 2017",
    url: "https://youtube.com/embed/o0BD3ok6Vq8",
    channel: {
      name: "Top Speed Tennis",
      logo: "https://yt3.ggpht.com/ytc/AAUvwnhWRW2ZbfLH00XzVcRH_ADen5YMM8dXTjuMNjwmhw=s88-c-k-c0x00ffffff-no-rj",
    },
    statistics: {
      views: 550005,
      likes: 5200,
      dislikes: 180,
    },
    description: `How would you like to gain more control in tennis?! How do we hold the racquet for the best stroke? For those looking to improve on their forehand, this video on Best Tennis Forehand Grip is for you. We have the tennis stroke, from forehand to serve, broken down to the most important keys in our Top Speed Tennis System. If you’re looking to get more from your forehand, we'll cover multiple grips, while improving key topspin generating fundamentals! Start having real control of your game. Become an ACE in tennis, we’ll teach you.
      I look forward to working with you much more in the future with Top Speed Tennis. Good luck with your tennis. 
      Clay Ballard
      `,
  },
  {
    title: "Tennis Backhand Grip (Top Speed Tennis)",
    thumbnail:
      "https://i.ytimg.com/vi/NoBdvxm-vho/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAxZGMTShQbxqFOZT-XGJQc9oqLaA",
    tags: ["tennis", "sport", "tennis grip"],
    category: ["grip"],
    uploaded: "Aug 22, 2014",
    url: "https://youtube.com/embed/NoBdvxm-vho",
    channel: {
      name: "Top Speed Tennis",
      logo: "https://yt3.ggpht.com/ytc/AAUvwnhWRW2ZbfLH00XzVcRH_ADen5YMM8dXTjuMNjwmhw=s88-c-k-c0x00ffffff-no-rj",
    },
    statistics: {
      views: 205930,
      likes: 2000,
      dislikes: 53,
    },
    description: `Have you been struggling with your backhand? Do you feel like your hand just can't get comfortable on the racket? Maybe you are struggling to get spin or a square racket at contact? 
      In this video I go through a series of drills that will allow you to ingraining the perfect backhand grips so that you will be able to automatically square up on those shots and start hitting the best backhands of your life. It all starts with the grip. 
      I look forward to working with you much more in the future with Top Speed Tennis. Good luck with your tennis. 
      Clay Ballard`,
  },
  {
    title: "How to put on a perfect tennis grip (overgrip)? 🎾",
    thumbnail:
      "https://i.ytimg.com/vi/Ov4QTPO08Uc/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAq8QloL7THnN3bm8vwl-41d3pD-A",

    tags: ["tennis", "sport", "tennis grip"],
    category: ["grip"],
    uploaded: "Nov 27, 2019",
    url: "https://youtube.com/embed/Ov4QTPO08Uc",
    channel: {
      name: "Tennis Spin",
      logo: "https://yt3.ggpht.com/ytc/AAUvwnj7sZyQMNY3Xc6bNKwxihCpY_7AsS6257PID4XN=s88-c-k-c0x00ffffff-no-rj",
    },
    statistics: {
      views: 140115,
      likes: 1400,
      dislikes: 63,
    },
    description: ``,
  },
  {
    title: "Two-Handed Backhand Fix",
    thumbnail:
      "https://i.ytimg.com/vi/Nx3fwCPzt5I/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAO1_NTvptyk9g3JeTgR33qMragLw",

    tags: ["tennis", "sport", "backhand", "training"],
    category: ["grip"],
    uploaded: "Sep 4, 2019",
    url: "https://youtube.com/embed/Nx3fwCPzt5I",
    channel: {
      name: "2MinuteTennis",
      logo: "https://yt3.ggpht.com/ytc/AAUvwnhBmfRokwrZJN92dyzER3i8TGJC1ugvl_8BfDtjoQ=s88-c-k-c0x00ffffff-no-rj",
    },
    statistics: {
      views: 138699,
      likes: 2700,
      dislikes: 74,
    },
    description: `Ryan explains to one of his video private lesson students how a two-handed backhand should be hit.`,
  },
  // worktout
  {
    title: "15 Minute Home Workout For Tennis Players",
    thumbnail:
      "https://i.ytimg.com/vi/-QSS3RAlslM/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBdU5WQOg-81VMoUAtj5L8fTZaAkA",

    tags: ["tennis", "sport", "workout"],
    category: ["workout"],
    uploaded: "Apr 18, 2020",
    url: "https://youtube.com/embed/-QSS3RAlslM",
    channel: {
      name: "Top Tennis Training - Pro Tennis Lessons",
      logo: "https://yt3.ggpht.com/ytc/AAUvwnidEDJaEpS0DizbYD_4EE7nL5EsalhRc4P80xIuVw=s88-c-k-c0x00ffffff-no-rj",
    },
    statistics: {
      views: 244651,
      likes: 5000,
      dislikes: 67,
    },
    description: ` Minute Home Workout For Tennis Players. In this new Top Tennis Training video, Coach Simon Konov will take you through a 15 minute home workout for tennis players. This workout consists of five, three-minute rounds with 30 seconds of rest between each round. If you feel like 15 minutes will be too intense, or maybe you're looking to do longer, you can always modify how many rounds you do, to suit your needs.
      If you enjoy the video, make sure you click the like button and subscribe to our channel and please make sure you turn on the notification bell so you get our latest videos, as soon as we release them.
      15 Minute Home Workout For Tennis Players:
      Round One
      Shadow Forehands - 30 seconds
      Hop and split-step alternating legs - 30 seconds
      Shadow Backhands - 30 seconds
      Normal press-ups - 30 seconds
      High knees - 30 seconds
      30 seconds break to reach the 3-minute mark
      Round Two
      Shadow forehand volleys - 30 seconds
      Double split steps -  30 seconds
      Shadow backhand volleys - 30 seconds
      Side steps on the spot - 30 seconds
      Russian twists with feet off ground -  30 seconds
      30 seconds break to reach the 6-minute mark
      Round Three
      Shadow Forehands - 30 seconds
      Crossover steps on spot - 30 seconds
      Shadow Backhand slice - 30 seconds
      Shoulder taps - 30 seconds
      Plank - 30 seconds
      30 seconds rest  to reach the 9 minute mark
      Round Four
      Forehand volley with two rackets -  30 seconds
      Split step into a crossover - 30 seconds
      Backhand volley with two rackets - 30 seconds
      Wide grip press-ups -  30 seconds
      Ab crunches -  30 seconds
      30-second rest to reach the 12 minute mark
      Round Five
      Forehands off one leg -  15 seconds each leg
      Double split steps - 30 seconds
      Backhands off one leg - 15 each leg
      Hop and split alternating - 30 seconds
      Knee to chest crunches -  30 seconds 
      Normal press-ups 30 seconds 
      15-minute workout complete
      #Home #Workout #StayHome`,
  },
  {
    title:
      "High Performance Tennis Training - Workout For Speed, Agility, Quickness and Conditioning",
    thumbnail:
      "https://i.ytimg.com/vi/hNochU1XpoA/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAyVVOWj7jwwGb3apBVOUgLVZE8hQ",
    tags: ["tennis", "sport", "workout"],
    category: ["workout"],
    uploaded: "Jan 10, 2019",
    url: "https://youtube.com/embed/hNochU1XpoA",
    channel: {
      name: "Essential Tennis - Lessons and Instruction for Passionate Players",
      logo: "https://yt3.ggpht.com/ytc/AAUvwng8rPyGGrs6Kzgq5x16ssURV-jeejchRp5Y9daYGg=s88-c-k-c0x00ffffff-no-rj",
    },
    statistics: {
      views: 143000,
      likes: 2500,
      dislikes: 52,
    },
    description: ``,
  },
  {
    title: "Tennis Workout - Top 5 Exercises For Tennis Players",
    thumbnail:
      "https://i.ytimg.com/vi/TCBaMGobwVI/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCieyf5qutp3fb4PppiJ3yDl5t87Q",

    tags: ["tennis", "sport", "workout"],
    category: ["workout"],
    uploaded: "Sep 3, 2018",
    url: "https://youtube.com/embed/TCBaMGobwVI",
    channel: {
      name: "Top Tennis Training - Pro Tennis Lessons",
      logo: "https://yt3.ggpht.com/ytc/AAUvwnidEDJaEpS0DizbYD_4EE7nL5EsalhRc4P80xIuVw=s88-c-k-c0x00ffffff-no-rj",
    },
    statistics: {
      views: 167000,
      likes: 4100,
      dislikes: 56,
    },
    description: `Tennis Workout - Top 5 Exercises For Tennis Players.
      This tennis workout routine can be done anywhere. You can use this tennis workout in the gym or this tennis workout on the court. You can also use this as a home tennis workout. There are many ways you can improve your tennis conditioning and get stronger for tennis without having to go to the gym.
      In this video Top Tennis Training coach Simon Konov will demonstrate five of the best exercises for tennis players.
      To do these you only need a resistance band.
      Tennis Workout:
      1. The first exercise is the jumping lunge. Great for developing explosive power in your legs, this will translate into stronger legs for wider balls, open stance shots, low volleys and cutting off wide returns.
      2. Exercise two is the explosive split step, you jump over a line and back to develop explosive power in the lower legs, the calf muscles. These muslces are responsible for your push off when split stepping and the first step to the ball. Build up these muscles and you'll be faster to the ball from the initial push.
      3. Exercise three will help you develop more rotational power through the trunk. The strong, explosive core is fundamental to playing tennis to a high level. These exercises will help you develop that explosive power for your tennis forehand and tennis backhand, along with your tennis return of serve.
      4. The fourth exercise is the reverse fly, this will help you build up a strong scapula region and the upper back muscles. These muslces are a big part of having a good posture and typically tennis players are much stronger in the chest and front shoulder muslces due to the forward phase of most tennis swings.
      5. The fifth exercise is for the rotator cuff muscle, located at the back of the shoulder. When we serve, we stress this region greatly, especially if we are serving a high speeds. That's why it's important to develop a strong shoulder region, to help prevent injuries and help you serve bigger.
      These five tennis specific exercises will be commonly used amongst pro tennis players as a basic workout routine.`,
  },
  {
    title: "Tennis Workout - Top 10 Exercises To Improve Your Game",
    thumbnail:
      "https://i.ytimg.com/vi/rqhDFwTFnes/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCzfiNs-oB0HFOwPFWJCh1oIeDwqg",

    tags: ["tennis", "sport", "workout"],
    category: ["workout"],
    uploaded: "Jun 20, 2020",
    url: "https://youtube.com/embed/rqhDFwTFnes",
    channel: {
      name: "Top Tennis Training - Pro Tennis Lessons",
      logo: "https://yt3.ggpht.com/ytc/AAUvwnidEDJaEpS0DizbYD_4EE7nL5EsalhRc4P80xIuVw=s88-c-k-c0x00ffffff-no-rj",
    },
    statistics: {
      views: 41000,
      likes: 1400,
      dislikes: 15,
    },
    description: `
        Tennis Workout - Top 10 Exercises To Improve Your Game
        When it comes to improving your game, many people think they need to spend countless hours simply hitting balls. That may make you a better ball striker, but it won't make you a tennis athlete. 
        To become faster on the court, reach more balls, have more power with your tennis forehand, backhand, and serve and be more explosive in your game, you need to do tennis-specific workouts.
        In this free tennis lesson, Top Tennis Training coach Simon Konov will show you a tennis workout that can be done on the tennis court, with 10 of the top exercises that tennis players can do to improve their game.
  
        Top 10 Exercises To Improve Your Game:
  
        Exercise One - Explosive Lateral Movement. Building explosive power in your leg muscles should be a major priority when you're training for tennis. In this drill, you start on one leg on one of the tramlines, then explode off the ground and jump over to the other tramline. There and back would equal one repetition, go for 8-10 in a row, and 2-3 sets of this drill.
        Exercise Two - Explosive Split Step. The split step is the most important footwork step in tennis, in this drill, you'll be building more explosive power for your split step and reinforce the motion. Set up a hurdle, it could be anything from 1-2 inches to a couple of feet, it will depend on your current fitness levels and what your body is capable of. Start behind the hurdle in your split step position and jump over the hurdle and back. That would be one rep, go for 8-10 reps per set and 2-3 sets of this drill.
        Exercise Three - Forearm Stability. When we make contact on any stroke, the racket is held in place, in large part by your wrist and forearm muscles. If you're weak in these areas, the racket is likely to move when you're dealing with a more powerful ball. In these two exercises, you'll be developing good strength in your forearm muscles. The first one is done with your palm facing the ground, let your wrist flop down into wrist flexion, and then bring your wrist up into wrist extension. Then return down into wrist flexion for one rep. Go for 10 reps per set with this drill. 
        The second exercise is for the opposite side of your forearm muscles, now you'll have your palm facing towards the sky and you'll start in wrist extension and then flex your forearm muscles so that your wrist ends up in wrist flexion. Once again go for 10 reps per set. With both of these exercises, you may need to do more than 3 sets, normally 4-5 sets work well in building up muscles in this region.
        Exercise Four - Core Stability. The plank is one of the best exercises for tennis players but it's also very stationary, a good alternative however is the press up into the plank position. Start off in a normal press-up position and then go into the plank position on your elbows, then return back into the press-up position, this would be one rep. Go for 10 reps per set and for 3 sets of this exercise.
        Exercise Five - Skipping. Skipping is one of the best ways you can improve your footwork for tennis. As you need to be light and use the balls of your feet when skipping, this mimics the exact motions we want to have when we're playing tennis, light, and on the balls of our feet when moving on the tennis court. There are three simple drills you can do to improve your tennis using skipping, the first one being normal skipping, the second drill is starting off with your feet together, and then going into a split step and the third drill is running on the spot. Go for 100 reps on each drill.
        Exercise Six - Leg Balance and Stability. One leg drills are a great way to develop explosive power in each leg but also develop great stability and balance. Federer uses one leg drills a lot in his training routine, it's one of the main reasons he's so explosive and powerful on court with his movement.
        If you can't move on one leg, you can simply shadow your forehand and backhand on one leg, on the spot. For the more advanced players out there, set up a few cones around 8-10 feet apart. Start at the first cone and then hop to the second cone, shadow your forehand or backhand stroke and return to the first cone. Go for 4-6 reps per set on each leg and 2-3 sets in total.
        Remember to work your weaker leg too!
        Video Timeline:
        00:00 - Why it's important to workout (intro)
        1:04 - Drill One (explosive push off)
        2:06 - Drill Two (split-step)
        4:30 - Drill Three (forearms)
        7:21 - Drill Four (core and upper body)
        8:08 - Drill Five (skipping footwork)
        9:40 - Drill Six (balance and explosive power)
        11:55 - Drill Seven (rotational power)
        13:57 - Drill Eight (back muscles)
        15:46 - Drill Nine (explosive forehands/backhands)
        17:23 - Drill Ten (recovery speed)
      `,
  },
  {
    title:
      "High Intensity Tennis Drills | Improve Your Footwork and Racquet Head Speed",
    thumbnail:
      "https://i.ytimg.com/vi/44_jvT6l-2E/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDfRzAnp96ISW6zLmUIJ8vpVJhENA",
    tags: ["tennis", "sport", "TennisForehand", "training", "intuitive tennis"],
    category: ["drills"],
    uploaded: "Jul 21, 2020",
    url: "https://youtube.com/embed/44_jvT6l-2E",
    channel: {
      name: "Intuitive Tennis",
      logo: "https://yt3.ggpht.com/ytc/AAUvwng1rygM9tMLbhN5T9-Aal8reInZoDBkf8kYJ9wC0A=s88-c-k-c0x00ffffff-no-rj",
    },
    statistics: {
      views: 582122,
      likes: 7100,
      dislikes: 125,
    },
    description: `
          In this practice session with former WTA player Ema Burgic Bucko who was ranked 466 in singles and 145 in doubles on the WTA rankings, we performed high intensity tennis drills that can improve your footwork and racquet head speed.  Execute the drills in the following order:
  
          0:00 Warm Up
          0:37 Low Balls
          1:22 High Balls
          1:45 Put Away Shots 
          3:16 Half Court Shots
          3:51 Swing Volleys
          4:28 Forehand Variations
          4:58 Racquet Head Speed
          5:27 FH's from the BH side
          5:45 Side to side
      `,
  },
];

module.exports = videos;
